name: NodeJs GitHub Action

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js

        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Deploy to Productions
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build]

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Install Render CLI
  #     run: |
  #       curl -fsSL https://cli.render.com/install.sh | sh
  #       # Ensure render CLI is installed and in PATH
  #       echo "Render CLI path:"
  #       which render || echo "Render CLI not found"
  #       render --version || echo "Failed to execute render command"
  #   - name: Deploy to Render
  #     run: render deploy --service ${{ secrets.RENDER_SERVICE_NAME }} --token ${{ secrets.RENDER_TOKEN }}
  #     env:
  #       RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
