name: NodeJs GitHub Action

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js

      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install
    - name: Run test
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v3
    - uses: akhileshns/heroku-deploy@v1.8.5
      with:
        heroku-api-key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app-name: 'node-github-action'
        heroku-email: 'preetbhingradiya.crawlapps@gmail.com'
